server:
  port: 8080

spring:
  application:
    name: Ut-It-Practice
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:UtIt-practice-db
    driver-class-name: org.h2.Driver
    username: root
    password: root